# Generated by Django 5.2.1 on 2025-05-23 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[(None, 'Select Provider'), ('google', 'Google'), ('github', 'Github'), ('sentinel', 'sentinel')], db_column='social_provider', max_length=10, unique=True)),
                ('client_id', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Social_Provider',
                'verbose_name_plural': 'Social_Providers',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=1000)),
                ('isConnected', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=1000, null=True, unique=True, validators=[django.core.validators.EmailValidator])),
                ('credentials', models.TextField(max_length=1000, null=True)),
                ('scopes', models.TextField(max_length=1000, null=True)),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socialaccount_site', to='sites.site')),
            ],
            options={
                'verbose_name': 'Social_Account',
                'verbose_name_plural': 'Social_Accounts',
            },
        ),
    ]
