# Generated by Django 5.2.1 on 2025-05-20 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otptoken',
            options={'ordering': ['user_id', '-created_at']},
        ),
        migrations.AddField(
            model_name='otptoken',
            name='expire_at',
            field=models.DateTimeField(auto_now=True, verbose_name='expire at'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='mobile_phone',
            field=models.CharField(blank=True, help_text='at most 19 characters of digits only', max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{8,15}$')], verbose_name='mobile phone'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Generated'), (2, 'Verified'), (3, 'Not Verified'), (0, 'EMPTY')], default=0, verbose_name='status'),
        ),
    ]
