# Generated by Django 2.2.23 on 2022-06-03 05:54

from django.db import migrations, models

import user.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20191218_1301'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emailuser',
            managers=[
                ('objects', user.models.EmailUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='emailuser',
            old_name='isEmailVerified',
            new_name='is_email_verified',
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='username',
            field=models.CharField(blank=True,
                                   help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                   max_length=50, null=True, unique=True),
        ),
    ]
